#############################################################################
# Copyright (c) 2025 CEA LIST.
#
# This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
# Marcos Didonet Del Fabro (CEA LIST) - Initial implementation
# Vincent Lorenzo (CEA LIST)
#############################################################################
workflow:
  rules:
    # 1. do nothing if we are not in the papyrus namespace
    - if: $CI_PROJECT_NAMESPACE != "eclipse/papyrus"
      when: never
    # 2. always launch a pipeline on MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    # 3. don't launch the branch pipeline if an MR exists
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # 4. launch for scheduled, MR IID, TAG and branches
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH #to launch a build on all branches of the Papyrus repo

include:
  - project: "eclipsefdn/it/releng/gitlab-runner-service/gitlab-ci-templates"
    file:
      - "/jobs/eca.gitlab-ci.yml"
      - "/jobs/buildkit.gitlab-ci.yml"
      - "/jobs/repo.eclipse.org.gitlab-ci.yml"
      - "/jobs/secrets.gitlab-ci.yml"

variables:
  MVN_TESTS_EXECUTIONS:
    value: ""
    description: "Indicates if we will execute the JUnit tests"
    options:
      - "-DskipTests" # no tests
      - "-DallTests" # all tests
      - "" # smoke tests

stages:
  - compliance
  - build
  - test
  - deploy

# Job to check ECA (Eclipse Contribution Agreement) for merge request.
# Note: this job has compliance stage (cf. parent job '.eca').
eca:
  extends: .eca
  rules:
    - when: always

# on all eclipse/papyrus branches, on schedule and commit tag ; no tests
build:
  stage: build
  tags:
    - ctx:medium
  needs:
    - job: "eca"
  image: maven:3.9.9-eclipse-temurin-21
  extends: .ef-repo-eclipse-org
  variables:
    MAVEN_OPTS: "-DskipTests -Dcheckstyle.skip -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DskipTests"
    NODE_VERSION: "22.16.0"
    NODE_DIR: "$CI_PROJECT_DIR/.node"
  secrets:
    GITHUB_COM_TOKEN:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
    PASSWORD:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
    REPO_USERNAME:
      vault: $EF_PROJECT_ID/repo.eclipse.org/username@cbi
      file: false
    REPO_PASSWORD:
      vault: $EF_PROJECT_ID/repo.eclipse.org/password@cbi
      file: false
  before_script:
    - mkdir -p "$NODE_DIR"
    - curl -o node.tar.gz -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
    - tar -xzf node.tar.gz --strip-components=1 -C "$NODE_DIR"
    - export PATH="$NODE_DIR/bin:$PATH"
    - node --version
  script:
    # Frontend build
    - pwd
    - echo '//npm.pkg.github.com/:_authToken=${GITHUB_COM_TOKEN}' >> frontend/.npmrc
    - cd frontend && npm install && npm ci && NODE_OPTIONS="--max-old-space-size=4096" npm run build
    - cd ..
    - mkdir -p backend/papyrus-web-frontend/src/main/resources/static
    - cp -R frontend/papyrus-web/dist/* backend/papyrus-web-frontend/src/main/resources/static

    # Conditional backend build/deploy
    - cd backend
    - mvn $MAVEN_CLI_OPTS verify --settings ../settings.xml
  artifacts:
    paths:
      - backend/papyrus-web/target/papyrus-web-*.jar
      - backend/papyrus-web/target/classes/
      - backend/papyrus-web/target/test-classes/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: "$CI_COMMIT_TAG != null"
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

  # Only on schedule and commit tag
deploy docker:
  stage: deploy
  tags:
    - ctx:medium
  needs:
    - job: "eca"
  after_script:
    - echo 'print image name'
    - echo "$CI_REGISTRY_IMAGE${CONTAINER_NAME:+/$CONTAINER_NAME}:$IMAGE_TAG"
    - echo -e "Building and shipping image to $CI_REGISTRY - $BUILD_IMAGE_NAME"
  extends:
    - .ef-buildkit
  variables:
    CI_REGISTRY_IMAGE: docker.io/eclipsepapyrus/papyrus-web
    PUSH_TO_REGISTRY: "true"
    BUILD_ARG: "--opt build-arg:PASSWORD=${GITHUB_COM_TOKEN}"
    DOCKERFILE_NAME: "dockerfiles/Dockerfile"
    IMAGE_TAG: "${CI_COMMIT_TAG:-latest}"
  secrets:
    GITHUB_COM_TOKEN:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
  rules:
    - if: "$CI_COMMIT_TAG != null" #if there is a tag, we publish a Docker image

# Only on schedule and commit tag
deploy maven:
  stage: deploy
  tags:
    - ctx:medium
  needs:
    - job: "eca"
  image: maven:3.9.9-eclipse-temurin-21
  extends: .ef-repo-eclipse-org
  variables:
    MAVEN_OPTS: "-Dcheckstyle.skip -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    # Conditional Maven goals - compile for nightly, deploy for releases
    MAVEN_CLI_OPTS: "-DskipTests --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
    NODE_VERSION: "22.16.0"
    NODE_DIR: "$CI_PROJECT_DIR/.node"
  secrets:
    GITHUB_COM_TOKEN:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
    PASSWORD:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
  before_script:
    - mkdir -p "$NODE_DIR"
    - curl -o node.tar.gz -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
    - tar -xzf node.tar.gz --strip-components=1 -C "$NODE_DIR"
    - export PATH="$NODE_DIR/bin:$PATH"
    - node --version
  script:
    # Frontend build
    - pwd
    - echo '//npm.pkg.github.com/:_authToken=${GITHUB_COM_TOKEN}' >> frontend/.npmrc
    - cd frontend && npm install && npm ci && NODE_OPTIONS="--max-old-space-size=4096" npm run build
    - cd ..
    - mkdir -p backend/papyrus-web-frontend/src/main/resources/static
    - cp -R frontend/papyrus-web/dist/* backend/papyrus-web-frontend/src/main/resources/static

    # Conditional backend build/deploy
    - cd backend
    - |
      if [ -z "${CI_COMMIT_TAG+x}" ]; then
        # commit tag is unset (null) - so we are building a snapshot
        # Snapshot build
        # extract version declared in pom.xml
        
        WEBAPP_DECLARED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        if [[ "$WEBAPP_DECLARED_VERSION" == *-SNAPSHOT ]]; then
           # already a snapshot -> insert commit SHA
           BASE_VERSION="${WEBAPP_DECLARED_VERSION%-SNAPSHOT}"
           SNAPSHOT_VERSION="${BASE_VERSION}-${CI_COMMIT_SHORT_SHA}-SNAPSHOT"
        else
           # it is a release version, convert it to a snapshot version + append commit SHA
           SNAPSHOT_VERSION="${WEBAPP_DECLARED_VERSION}-${CI_COMMIT_SHORT_SHA}-SNAPSHOT"
        fi
        echo "tag is unset - build and deploy a snapshot"
        echo "Setting Maven version to: $SNAPSHOT_VERSION"
        mvn versions:set -DnewVersion="$SNAPSHOT_VERSION" -DprocessAllModules=true
        mvn versions:commit
      fi
    - mvn $MAVEN_CLI_OPTS clean deploy --settings ../settings.xml
  artifacts:
    paths:
      - backend/papyrus-web/target/papyrus-web-*.jar
      - backend/papyrus-web/target/classes/
      - backend/papyrus-web/target/test-classes/
      - backend/papyrus-web/target/surefire-reports/
    expire_in: 1 week
  rules:
    # we will publish the mvn packages only for master branch, on scheduled job (latest version) or for tagged commits
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # not on master branch
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: "$CI_COMMIT_TAG != null"

deploy npm:
    stage: deploy
    tags:
      - ctx:medium
    needs:
      -  job: "eca"
    image: maven:3.9.9-eclipse-temurin-21
    extends:
      - .ef-repo-eclipse-org
      - .secrets
    variables:
      NODE_VERSION: "22.16.0"
      NODE_DIR: "$CI_PROJECT_DIR/.node"
    id_tokens:
      VAULT_ID_TOKEN:
        aud: https://gitlab.eclipse.org
      SIGSTORE_ID_TOKEN:
        aud: sigstore
    secrets:
      GITHUB_COM_TOKEN:
        vault: $EF_PROJECT_ID/github.com/registry-token@cbi
        file: false
      PASSWORD:
        vault: $EF_PROJECT_ID/github.com/registry-token@cbi
        file: false
      REPO_USERNAME:
        vault: $EF_PROJECT_ID/repo.eclipse.org/username@cbi
        file: false
      REPO_PASSWORD:
        vault: $EF_PROJECT_ID/repo.eclipse.org/password@cbi
        file: false
      NPM_TOKEN:
       vault: $EF_PROJECT_ID/npmjs.com/token@cbi
       file: false
    before_script:
      - mkdir -p "$NODE_DIR"
      - curl -o node.tar.gz -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
      - tar -xzf node.tar.gz --strip-components=1 -C "$NODE_DIR"
      - export PATH="$NODE_DIR/bin:$PATH"
      - node --version
    script:
      - pwd
      - echo '//npm.pkg.github.com/:_authToken=${GITHUB_COM_TOKEN}' >> frontend/.npmrc
      - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - cd frontend
      - npm ci
      - NODE_OPTIONS="--max-old-space-size=4096"
      - npm run build
      - npm publish --workspaces --access public
    artifacts:
      paths:
        - frontend/node_modules/
      expire_in: 1 week
    rules:
      # we will publish the npm packages only for tagged commits from master branch
      - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # not on master branch
        when: never
      - if: "$CI_COMMIT_TAG != null"

smoke tests:
  extends: .runTests
  variables:
    MVN_TESTS_EXECUTIONS: "" # execute just the smoke tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # on MR
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # on developper branch

all tests:
  extends: .runTests
  variables:
    MVN_TESTS_EXECUTIONS: "-DallTests" # execute all the tests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # on MR
    - if: $CI_PIPELINE_SOURCE == "schedule"

.runTests:
  stage: test
  tags:
    - ctx:medium
  needs:
    - job: "build"
      artifacts: true
  services:
    - name: quay.io/sclorg/postgresql-15-c9s
      alias: postgres
  image: cypress/included:12.17.4
  extends: .ef-repo-eclipse-org
  variables:
    MAVEN_VERSION: "3.9.9"
    NODE_VERSION: "22.16.0"
    NODE_DIR: "$CI_PROJECT_DIR/.node"
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=false -DdeployAtEnd=false $MVN_TESTS_EXECUTIONS -Dpapyrusweb.testcontainers.use=false"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/papyrus-web-db"
    PAPYRUSWEB_INTEGRATION_TESTS_DATASOURCE_URL: "jdbc:postgresql://postgres/papyrus-web-db"
    PAPYRUSWEB_INTEGRATION_TESTS_DATASOURCE_USERNAME: "dbuser"
    PAPYRUSWEB_INTEGRATION_TESTS_DATASOURCE_PASSWORD: "dbpwd"
    POSTGRESQL_DATABASE: papyrus-web-db
    POSTGRESQL_USER: dbuser
    POSTGRESQL_PASSWORD: dbpwd
  secrets:
    GITHUB_COM_TOKEN:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
    PASSWORD:
      vault: $EF_PROJECT_ID/github.com/registry-token@cbi
      file: false
  before_script:
    # Install Node.js
    #- mkdir -p "$NODE_DIR"
    # curl -o node.tar.gz -fsSL "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
    #- wget https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz
    #- tar -xzf node-v$NODE_VERSION-linux-x64.tar.gz --strip-components=1 -C "$NODE_DIR"
    #- export PATH="$NODE_DIR/bin:$PATH"
    # Install Maven
    - wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
    - tar -xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz
    - export PATH=./apache-maven-$MAVEN_VERSION/bin:$PATH
    # Install Java 21
    - wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_x64_linux_hotspot_21.0.11_10.tar.gz
    - tar -xzvf OpenJDK21U-jdk_x64_linux_hotspot_21.0.11_10.tar.gz
    - export JAVA_HOME=./jdk-21.0.11+10
    - export PATH=$JAVA_HOME/bin:$PATH
  script:
    # Backend tests
    - mvn $MAVEN_CLI_OPTS test -f backend/pom.xml --settings settings.xml
    - export WEBAPP_VERSION=$(grep version frontend/package.json | awk -F \" '{print $4}')

    # Start backend for Cypress tests in background
    #- java -Dsirius.components.cors.allowedCredentials=true -Dsirius.components.cors.allowedOriginPatterns=* -jar backend/papyrus-web/target/papyrus-web-$WEBAPP_VERSION.jar --spring.datasource.url=$SPRING_DATASOURCE_URL --spring.datasource.username=$SPRING_DATASOURCE_USERNAME --spring.datasource.password=$SPRING_DATASOURCE_PASSWORD --spring.liquibase.change-log=classpath:db/changelog/papyrus-web.db.changelog.xml &
    #- BACKEND_PID=$!

    # Wait for the backend to start
    #- sleep 200

    # Cypress tests
    #- cd integration-tests
    #- npm install
    #- npx cypress run

    # Stop the backend server
    #- kill $BACKEND_PID
  artifacts:
    paths:
      - backend/papyrus-web/target/papyrus-web-*.jar
      - backend/papyrus-web/target/classes/
      - backend/papyrus-web/target/test-classes/
      - backend/papyrus-web/target/surefire-reports/
      - backend/papyrus-web-test-coverage/target/site/jacoco-aggregate/
    reports:
      junit:
        - backend/**/target/surefire-reports/*.xml
      #- integration-tests/cypress/screenshots/
      #- integration-tests/cypress/videos/
      #- integration-tests/cypress/results/
      #- integration-tests/cypress/reports/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"

cypress tests:
  stage: test
  tags:
    - ctx:medium
  needs:
    - job: "build"
      artifacts: true
  services:
    - name: quay.io/sclorg/postgresql-15-c9s
      alias: postgres
  image: cypress/included:12.17.4
  extends: .ef-repo-eclipse-org
  variables:
    NODE_VERSION: "22.16.0"
    NODE_DIR: "$CI_PROJECT_DIR/.node"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/papyrus-web-db"
    POSTGRESQL_DATABASE: papyrus-web-db # used by the postgre image
    POSTGRESQL_USER: dbuser # used by the postgre image
    POSTGRESQL_PASSWORD: dbpwd # used by the postgre image
    SPRING_DATASOURCE_USERNAME: dbuser
    SPRING_DATASOURCE_PASSWORD: dbpwd
  before_script:
    # Install Node.js
    - mkdir -p "$NODE_DIR"
    - wget https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz
    - tar -xzf node-v$NODE_VERSION-linux-x64.tar.gz --strip-components=1 -C "$NODE_DIR"
    - export PATH="$NODE_DIR/bin:$PATH"
    # Install Java 21
    - wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_x64_linux_hotspot_21.0.11_10.tar.gz
    - tar -xzvf OpenJDK21U-jdk_x64_linux_hotspot_21.0.11_10.tar.gz
    - export JAVA_HOME=./jdk-21.0.11+10
    - export PATH=$JAVA_HOME/bin:$PATH
  script:
    # Start backend for Cypress tests in background
    - export WEBAPP_VERSION=$(grep version frontend/package.json | awk -F \" '{print $4}')
    - java -Dsirius.components.cors.allowedCredentials=true -Dsirius.components.cors.allowedOriginPatterns=* -jar backend/papyrus-web/target/papyrus-web-$WEBAPP_VERSION.jar --spring.datasource.url=$SPRING_DATASOURCE_URL --spring.datasource.username=$SPRING_DATASOURCE_USERNAME --spring.datasource.password=$SPRING_DATASOURCE_PASSWORD --spring.liquibase.change-log=classpath:db/changelog/papyrus-web.db.changelog.xml &
    - BACKEND_PID=$!

    # Wait for the backend to start
    - sleep 200 # required

    # Cypress tests
    - cd integration-tests
    - npm install
    - npx cypress run --config baseUrl=http://127.0.0.1:8080 --env baseAPIUrl=http://127.0.0.1:8080

    # Stop the backend server
    - kill $BACKEND_PID
  artifacts:
    when: always
    paths:
      - integration-tests/target/screenshots/**/*.png
    reports:
      junit:
        - integration-tests/target/*.xml
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH # on developper branch
