#!/bin/sh

VERSION="$1"
mvn versions:set -DgroupId=papyrus-web -DartifactId="*" -DoldVersion="*" -DnewVersion="$VERSION" -f backend/pom.xml

cd frontend
npm version "$VERSION"  --commit-hooks=false --git-tag-version=false --workspaces=true --include-workspace-root=true --workspaces-update=false
npm i
cd ..

cd integration-tests
npm version "$VERSION"  --commit-hooks=false --git-tag-version=false --workspaces=false --include-workspace-root=false --workspaces-update=false
npm i
cd ..